### ISSUE TITLE
2.0.0 Release Work

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/bunnybus-cli#1]
### Context

This is an issue tracket to help as a high level checklist for items needing to be accomplished

## TODO

- [x] grep all `TODO` in code base and fix
- [x] implement `-G` option
  - [x] create a `BunnyBusGetReader` Readable Stream
- [x] implement `-t` option
  - [x] add a `process.stdout` write option based on this switch for `Writables`
- [x] implement `-m` option
  - [x] open up the feature for exporting and importing meta information from 
`payload.properties.headers` when the flag is on
- [x] implement `-v <path>` option
  - [x] this turns on logging and directs output to the provided file.
  - [x] create a file stream for the output.
- [x] API documentation
  - [x] TOC listing
  - [x] `bunnybus` command
  - [x] `bb-stream-output` command
  - [x] Major Options
  - [x] Minor Options
- [x] Example Documentation
  - [x] Show exact output for the minor options
  - [x] Show how to combine the commands together
